[package]
name = "bitcoin_key_hunter"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
bitcoin = { version = "0.30", features = ["std", "secp-recovery"] }
secp256k1 = { version = "0.27", features = ["rand"] }
hex = "0.4"
ctrlc = "3.2"
num_cpus = "1.13"